lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("<str:name>", views.greet, name="greet"),
    path('brian', views.brian, name='brian'),
    path('david', views.david, name='david'),
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/',include("newyear.urls")),
    path('tasks/',include("tasks.urls")),
]

lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name ="index")
]

lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

movieapp/urls.py
from django.urls import include, path

"""
URL configuration for movieapp project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
# http://127.0.0.1:8000/movies
# http://127.0.0.1:8000/movies/3
# http://127.0.0.1:8000/movies/walking-dead
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls'))
]

movies/urls.py
from django.urls import path
from . import views

# http://127.0.0.1:8000/
# http://127.0.0.1:8000/home
# http://127.0.0.1:8000/movies
# http://127.0.0.1:8000/movies/3
# http://127.0.0.1:8000/movies/walking-dead

urlpatterns = [
    path("", views.home),
    path("home", views.home),
    path("movies", views.movies),
]

lecture3/hello/models.py
from django.db import models

# Create your models here.

lecture3/newyear/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

movies/models.py
from django.db import models


class Category(models.Model): 
    name = models.CharField(max_length=100)

class Movie(models.Model): 
    film_adi = models.CharField(max_length=200)
    aciklama = models.TextField()
    resim = models.CharField(max_length=100)
    anasayfa = models.BooleanField(default=False)

account/views.py
from django.shortcuts import render

# Create your views here.

lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian")

def david(request): 
    return HttpResponse("Hello, David")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

lecture3/newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

lecture3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse



class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST": 
        form = NewTaskForm(request.POST)
        if form.is_valid():
           task = form.cleaned_data["task"]
           request.session["tasks"] += [task]
           return HttpResponseRedirect(reverse("tasks:index"))
        else: 
            return render(request, "tasks/add.html", {
                "form": form
            }) 
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

movies/views.py
from django.shortcuts import render
from .models import Category, Movie

kategori_liste = ["macera", "romantik", "dram", "bilim kurgu"]
film_liste = [
    {
    "film_adi": "film 1",
    "aciklama": "film 1 aciklama",
    "resim": "https://picsum.photos/200/300?random=1",
    "anasayfa": True
    },
    {
        "film_adi": "film 2",
        "aciklama": "film 2 aciklama",
        "resim": "https://picsum.photos/200/300?random=2",
        "anasayfa": True
    },
    {
        "film_adi": "film 3",
        "aciklama": "film 3 aciklama",
        "resim": "https://picsum.photos/200/300?random=3",
        "anasayfa": False
    },
    {
        "film_adi": "film 4",
        "aciklama": "film 4 aciklama",
        "resim": "https://picsum.photos/200/300?random=4",
        "anasayfa": False
    }
]

def home(request): 
    data = {
        "kategoriler": Category.objects.all(),
        "filmler": Movie.objects.filter(anasayfa=True)
    }
    return render(request,"index.html", data)

def movies(request): 
    data = {
        "kategoriler": Category.objects.all(),
        "filmler": Movie.objects.all()
    }
    return render(request,"movies.html", data)

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello {{name}} </h1>
</body>
</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello! html page</h1>
</body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Year's</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

lecture3/tasks/templates/tasks/add.html
{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
        <h1>Tasks</h1>
        <ul>
            {% for task in tasks %} 
                <li>{{ task }}</li>
                {% empty %}
                <li>No tasks yet</li>
            {% endfor %}
        </ul> 
        <a href="{% url 'tasks:add' %}">Add a New Task</a>
    {% endblock %}
</body>
</html>

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

movies/templates/index.html
<h1>Home page</h1>

<ul>
    {% for kategori in kategoriler %}
    <li>{{kategori.name}}</li>
    {% endfor %}
</ul>


<div id="filmler">
    {% for film in filmler %} 
        {% if film.anasayfa %}
        <div>
            <p>{{film.film_adi}}</p>
            <p>{{film.aciklama}}</p>
            <img src="{{film.resim}}" alt="">
        </div>
        {% endif %}
    {% endfor %}
</div>

movies/templates/movies.html
<h1>Movies</h1>

<ul>
    {% for kategori in kategoriler %}
    <li>{{kategori.name}}</li>
    {% endfor %}
</ul>


<div id="filmler">
    {% for film in filmler %}
    <div>
        <p>{{film.film_adi}}</p>
        <p>{{film.aciklama}}</p>
        <img src="{{film.resim}}" alt="">
    </div>
    {% endfor %}
</div>